---
- hosts: printServer
  become: true

  pre_tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure dependencies are installed (Debian)
      ansible.builtin.apt:
        name:
          - cups
          - samba
          - hplip
        state: present
      when: ansible_facts.os_family == "Debian"

  handlers:
  - name: Include handlers.
    ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup CUPS
      ansible.builtin.import_tasks: tasks/cups.yml
    
    - name: Setup SAMBA
      ansible.builtin.import_tasks: tasks/samba.yml